project:
  type: book
  output-dir: docs
  
  
book: 
   title: "Business Analytics"

   author: "Shu Han"
   chapters:
    - index.qmd
    - chapters/01-functions.qmd
  

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
  epub: default
  pdf:
    documentclass: scrbook

